// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	models "github.com/gpabois/cougnat/reporting/models"
	mock "github.com/stretchr/testify/mock"

	option "github.com/gpabois/cougnat/core/option"

	result "github.com/gpabois/cougnat/core/result"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: report
func (_m *ReportRepository) Create(report models.Report) result.Result[string] {
	ret := _m.Called(report)

	var r0 result.Result[string]
	if rf, ok := ret.Get(0).(func(models.Report) result.Result[string]); ok {
		r0 = rf(report)
	} else {
		r0 = ret.Get(0).(result.Result[string])
	}

	return r0
}

// ReportRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - report models.Report
func (_e *ReportRepository_Expecter) Create(report interface{}) *ReportRepository_Create_Call {
	return &ReportRepository_Create_Call{Call: _e.mock.On("Create", report)}
}

func (_c *ReportRepository_Create_Call) Run(run func(report models.Report)) *ReportRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Report))
	})
	return _c
}

func (_c *ReportRepository_Create_Call) Return(_a0 result.Result[string]) *ReportRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportRepository_Create_Call) RunAndReturn(run func(models.Report) result.Result[string]) *ReportRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: reportID
func (_m *ReportRepository) Delete(reportID string) result.Result[bool] {
	ret := _m.Called(reportID)

	var r0 result.Result[bool]
	if rf, ok := ret.Get(0).(func(string) result.Result[bool]); ok {
		r0 = rf(reportID)
	} else {
		r0 = ret.Get(0).(result.Result[bool])
	}

	return r0
}

// ReportRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReportRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - reportID string
func (_e *ReportRepository_Expecter) Delete(reportID interface{}) *ReportRepository_Delete_Call {
	return &ReportRepository_Delete_Call{Call: _e.mock.On("Delete", reportID)}
}

func (_c *ReportRepository_Delete_Call) Run(run func(reportID string)) *ReportRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReportRepository_Delete_Call) Return(_a0 result.Result[bool]) *ReportRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportRepository_Delete_Call) RunAndReturn(run func(string) result.Result[bool]) *ReportRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *ReportRepository) GetById(id string) result.Result[option.Option[models.Report]] {
	ret := _m.Called(id)

	var r0 result.Result[option.Option[models.Report]]
	if rf, ok := ret.Get(0).(func(string) result.Result[option.Option[models.Report]]); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(result.Result[option.Option[models.Report]])
	}

	return r0
}

// ReportRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type ReportRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id string
func (_e *ReportRepository_Expecter) GetById(id interface{}) *ReportRepository_GetById_Call {
	return &ReportRepository_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *ReportRepository_GetById_Call) Run(run func(id string)) *ReportRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReportRepository_GetById_Call) Return(_a0 result.Result[option.Option[models.Report]]) *ReportRepository_GetById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReportRepository_GetById_Call) RunAndReturn(run func(string) result.Result[option.Option[models.Report]]) *ReportRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewReportRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReportRepository(t mockConstructorTestingTNewReportRepository) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
