// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/gpabois/cougnat/monitoring/models"
	mock "github.com/stretchr/testify/mock"

	reportingmodels "github.com/gpabois/cougnat/reporting/models"

	repositories "github.com/gpabois/cougnat/monitoring/repositories"

	result "github.com/gpabois/cougnat/core/result"

	slippy_map "github.com/gpabois/cougnat/core/slippy-map"
)

// IPolMapRepository is an autogenerated mock type for the IPolMapRepository type
type IPolMapRepository struct {
	mock.Mock
}

type IPolMapRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPolMapRepository) EXPECT() *IPolMapRepository_Expecter {
	return &IPolMapRepository_Expecter{mock: &_m.Mock}
}

// DecPollutionTileMany provides a mock function with given fields: index, reportType
func (_m *IPolMapRepository) DecPollutionTileMany(index models.TimeTileIndex, reportType reportingmodels.ReportType) result.Result[bool] {
	ret := _m.Called(index, reportType)

	var r0 result.Result[bool]
	if rf, ok := ret.Get(0).(func(models.TimeTileIndex, reportingmodels.ReportType) result.Result[bool]); ok {
		r0 = rf(index, reportType)
	} else {
		r0 = ret.Get(0).(result.Result[bool])
	}

	return r0
}

// IPolMapRepository_DecPollutionTileMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecPollutionTileMany'
type IPolMapRepository_DecPollutionTileMany_Call struct {
	*mock.Call
}

// DecPollutionTileMany is a helper method to define mock.On call
//   - index models.TimeTileIndex
//   - reportType reportingmodels.ReportType
func (_e *IPolMapRepository_Expecter) DecPollutionTileMany(index interface{}, reportType interface{}) *IPolMapRepository_DecPollutionTileMany_Call {
	return &IPolMapRepository_DecPollutionTileMany_Call{Call: _e.mock.On("DecPollutionTileMany", index, reportType)}
}

func (_c *IPolMapRepository_DecPollutionTileMany_Call) Run(run func(index models.TimeTileIndex, reportType reportingmodels.ReportType)) *IPolMapRepository_DecPollutionTileMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.TimeTileIndex), args[1].(reportingmodels.ReportType))
	})
	return _c
}

func (_c *IPolMapRepository_DecPollutionTileMany_Call) Return(_a0 result.Result[bool]) *IPolMapRepository_DecPollutionTileMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPolMapRepository_DecPollutionTileMany_Call) RunAndReturn(run func(models.TimeTileIndex, reportingmodels.ReportType) result.Result[bool]) *IPolMapRepository_DecPollutionTileMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetPollutionTimeSlice provides a mock function with given fields: ur, dl, begin, end
func (_m *IPolMapRepository) GetPollutionTimeSlice(ur slippy_map.TileIndex, dl slippy_map.TileIndex, begin int, end int) result.Result[models.PolTimeSlice] {
	ret := _m.Called(ur, dl, begin, end)

	var r0 result.Result[models.PolTimeSlice]
	if rf, ok := ret.Get(0).(func(slippy_map.TileIndex, slippy_map.TileIndex, int, int) result.Result[models.PolTimeSlice]); ok {
		r0 = rf(ur, dl, begin, end)
	} else {
		r0 = ret.Get(0).(result.Result[models.PolTimeSlice])
	}

	return r0
}

// IPolMapRepository_GetPollutionTimeSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPollutionTimeSlice'
type IPolMapRepository_GetPollutionTimeSlice_Call struct {
	*mock.Call
}

// GetPollutionTimeSlice is a helper method to define mock.On call
//   - ur slippy_map.TileIndex
//   - dl slippy_map.TileIndex
//   - begin int
//   - end int
func (_e *IPolMapRepository_Expecter) GetPollutionTimeSlice(ur interface{}, dl interface{}, begin interface{}, end interface{}) *IPolMapRepository_GetPollutionTimeSlice_Call {
	return &IPolMapRepository_GetPollutionTimeSlice_Call{Call: _e.mock.On("GetPollutionTimeSlice", ur, dl, begin, end)}
}

func (_c *IPolMapRepository_GetPollutionTimeSlice_Call) Run(run func(ur slippy_map.TileIndex, dl slippy_map.TileIndex, begin int, end int)) *IPolMapRepository_GetPollutionTimeSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(slippy_map.TileIndex), args[1].(slippy_map.TileIndex), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *IPolMapRepository_GetPollutionTimeSlice_Call) Return(_a0 result.Result[models.PolTimeSlice]) *IPolMapRepository_GetPollutionTimeSlice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPolMapRepository_GetPollutionTimeSlice_Call) RunAndReturn(run func(slippy_map.TileIndex, slippy_map.TileIndex, int, int) result.Result[models.PolTimeSlice]) *IPolMapRepository_GetPollutionTimeSlice_Call {
	_c.Call.Return(run)
	return _c
}

// IncPollutionTileMany provides a mock function with given fields: commands
func (_m *IPolMapRepository) IncPollutionTileMany(commands []repositories.IncPollutionCommand) result.Result[bool] {
	ret := _m.Called(commands)

	var r0 result.Result[bool]
	if rf, ok := ret.Get(0).(func([]repositories.IncPollutionCommand) result.Result[bool]); ok {
		r0 = rf(commands)
	} else {
		r0 = ret.Get(0).(result.Result[bool])
	}

	return r0
}

// IPolMapRepository_IncPollutionTileMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncPollutionTileMany'
type IPolMapRepository_IncPollutionTileMany_Call struct {
	*mock.Call
}

// IncPollutionTileMany is a helper method to define mock.On call
//   - commands []repositories.IncPollutionCommand
func (_e *IPolMapRepository_Expecter) IncPollutionTileMany(commands interface{}) *IPolMapRepository_IncPollutionTileMany_Call {
	return &IPolMapRepository_IncPollutionTileMany_Call{Call: _e.mock.On("IncPollutionTileMany", commands)}
}

func (_c *IPolMapRepository_IncPollutionTileMany_Call) Run(run func(commands []repositories.IncPollutionCommand)) *IPolMapRepository_IncPollutionTileMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]repositories.IncPollutionCommand))
	})
	return _c
}

func (_c *IPolMapRepository_IncPollutionTileMany_Call) Return(_a0 result.Result[bool]) *IPolMapRepository_IncPollutionTileMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPolMapRepository_IncPollutionTileMany_Call) RunAndReturn(run func([]repositories.IncPollutionCommand) result.Result[bool]) *IPolMapRepository_IncPollutionTileMany_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewIPolMapRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPolMapRepository creates a new instance of IPolMapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPolMapRepository(t mockConstructorTestingTNewIPolMapRepository) *IPolMapRepository {
	mock := &IPolMapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
