// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReportEventReceiver is an autogenerated mock type for the ReportEventReceiver type
type ReportEventReceiver struct {
	mock.Mock
}

type ReportEventReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportEventReceiver) EXPECT() *ReportEventReceiver_Expecter {
	return &ReportEventReceiver_Expecter{mock: &_m.Mock}
}

// OnDeletedReport provides a mock function with given fields: report
func (_m *ReportEventReceiver) OnDeletedReport(report string) {
	_m.Called(report)
}

// ReportEventReceiver_OnDeletedReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDeletedReport'
type ReportEventReceiver_OnDeletedReport_Call struct {
	*mock.Call
}

// OnDeletedReport is a helper method to define mock.On call
//   - report string
func (_e *ReportEventReceiver_Expecter) OnDeletedReport(report interface{}) *ReportEventReceiver_OnDeletedReport_Call {
	return &ReportEventReceiver_OnDeletedReport_Call{Call: _e.mock.On("OnDeletedReport", report)}
}

func (_c *ReportEventReceiver_OnDeletedReport_Call) Run(run func(report string)) *ReportEventReceiver_OnDeletedReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReportEventReceiver_OnDeletedReport_Call) Return() *ReportEventReceiver_OnDeletedReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportEventReceiver_OnDeletedReport_Call) RunAndReturn(run func(string)) *ReportEventReceiver_OnDeletedReport_Call {
	_c.Call.Return(run)
	return _c
}

// OnNewReport provides a mock function with given fields: report
func (_m *ReportEventReceiver) OnNewReport(report string) {
	_m.Called(report)
}

// ReportEventReceiver_OnNewReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnNewReport'
type ReportEventReceiver_OnNewReport_Call struct {
	*mock.Call
}

// OnNewReport is a helper method to define mock.On call
//   - report string
func (_e *ReportEventReceiver_Expecter) OnNewReport(report interface{}) *ReportEventReceiver_OnNewReport_Call {
	return &ReportEventReceiver_OnNewReport_Call{Call: _e.mock.On("OnNewReport", report)}
}

func (_c *ReportEventReceiver_OnNewReport_Call) Run(run func(report string)) *ReportEventReceiver_OnNewReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReportEventReceiver_OnNewReport_Call) Return() *ReportEventReceiver_OnNewReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportEventReceiver_OnNewReport_Call) RunAndReturn(run func(string)) *ReportEventReceiver_OnNewReport_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewReportEventReceiver interface {
	mock.TestingT
	Cleanup(func())
}

// NewReportEventReceiver creates a new instance of ReportEventReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReportEventReceiver(t mockConstructorTestingTNewReportEventReceiver) *ReportEventReceiver {
	mock := &ReportEventReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
