// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/gpabois/cougnat/reporting/models"
	mock "github.com/stretchr/testify/mock"

	result "github.com/gpabois/cougnat/core/result"
)

// IReportService is an autogenerated mock type for the IReportService type
type IReportService struct {
	mock.Mock
}

type IReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *IReportService) EXPECT() *IReportService_Expecter {
	return &IReportService_Expecter{mock: &_m.Mock}
}

// DeleteReport provides a mock function with given fields: ctx, reportID
func (_m *IReportService) DeleteReport(ctx context.Context, reportID string) result.Result[string] {
	ret := _m.Called(ctx, reportID)

	var r0 result.Result[string]
	if rf, ok := ret.Get(0).(func(context.Context, string) result.Result[string]); ok {
		r0 = rf(ctx, reportID)
	} else {
		r0 = ret.Get(0).(result.Result[string])
	}

	return r0
}

// IReportService_DeleteReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReport'
type IReportService_DeleteReport_Call struct {
	*mock.Call
}

// DeleteReport is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID string
func (_e *IReportService_Expecter) DeleteReport(ctx interface{}, reportID interface{}) *IReportService_DeleteReport_Call {
	return &IReportService_DeleteReport_Call{Call: _e.mock.On("DeleteReport", ctx, reportID)}
}

func (_c *IReportService_DeleteReport_Call) Run(run func(ctx context.Context, reportID string)) *IReportService_DeleteReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IReportService_DeleteReport_Call) Return(_a0 result.Result[string]) *IReportService_DeleteReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IReportService_DeleteReport_Call) RunAndReturn(run func(context.Context, string) result.Result[string]) *IReportService_DeleteReport_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function with given fields: ctx, report
func (_m *IReportService) Report(ctx context.Context, report models.Report) result.Result[models.Report] {
	ret := _m.Called(ctx, report)

	var r0 result.Result[models.Report]
	if rf, ok := ret.Get(0).(func(context.Context, models.Report) result.Result[models.Report]); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Get(0).(result.Result[models.Report])
	}

	return r0
}

// IReportService_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type IReportService_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
//   - ctx context.Context
//   - report models.Report
func (_e *IReportService_Expecter) Report(ctx interface{}, report interface{}) *IReportService_Report_Call {
	return &IReportService_Report_Call{Call: _e.mock.On("Report", ctx, report)}
}

func (_c *IReportService_Report_Call) Run(run func(ctx context.Context, report models.Report)) *IReportService_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Report))
	})
	return _c
}

func (_c *IReportService_Report_Call) Return(_a0 result.Result[models.Report]) *IReportService_Report_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IReportService_Report_Call) RunAndReturn(run func(context.Context, models.Report) result.Result[models.Report]) *IReportService_Report_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewIReportService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIReportService creates a new instance of IReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIReportService(t mockConstructorTestingTNewIReportService) *IReportService {
	mock := &IReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
